<?
$limitar_ext = "sim";
//limitar o tipo de arquivo (Sim ou Não)

$extensoes_validas=array(".gif",".jpg",".jpeg", ".bmp");
// extensões permitidas

$caminho_absoluto  = "C:\wamp64\www\imobbgestor\assets\img";
//aqui deverá entrar o caminho para o upload (caminho servidor)

$limitar_tamanho = "sim";
// limitar o tamanho do arquivo?

$tamanho_bytes = "400000";
//tamanho limite do arquivo em bytes

$sobrescrever = "sim";
//se já existir o arquivo deseja sobrescrever?
?>

